[package]
name = "evo-desktop"
version = "1.2.0"
description = "EVO desktop client"
authors = ["EVO"]
edition = "2021"

[lib]
name = "evo_desktop_lib"
crate-type = ["staticlib", "rlib"]

[workspace]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-autostart = "2"
tauri-plugin-process = "2"

[features]
custom-protocol = ["tauri/custom-protocol"]
